services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: L4Vz0iku2ybc844EdpUp
      DB_HOST: bia.cmpyakeyas3w.us-east-1.rds.amazonaws.com
      DB_PORT: 5432