services:
  server:
    build: .
    container_name: ${DB_NAME}
    ports:
      - 80:8080
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PWD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}